cmake_minimum_required(VERSION 3.20)
project (kfwlogon LANGUAGES C)

set(CMAKE_RC_FLAGS "WIN32 RES_ONLY")
set(RESOURCES "${ROOT_DIR}/windows/version.rc")

set(TARGET_LIB_NAME kfwlogon)
set(TARGET_BIN_NAME kfwcpcc)

set(TARGET_INCLUDES)
set(TARGET_LIBRARIES)

# list(APPEND MODULE_INCLUDE_DIRECTORIES ${CMAKE_BINARY_DIR}/generated)
file(GLOB_RECURSE SOURCES "*.c")
file(GLOB_RECURSE HEADERS "*.h")

list(APPEND TARGET_INCLUDES "${ROOT_INCLUDE_DIR}")
list(APPEND TARGET_INCLUDES "${WINVER_INCLUDE_DIR}")
list(APPEND TARGET_INCLUDES "${KRB5_INCLUDE_DIR}")
list(APPEND TARGET_INCLUDES "${UTIL_ET_INCLUDE_DIR}")

list(APPEND TARGET_LIBRARIES "kernel32")
list(APPEND TARGET_LIBRARIES "user32")
list(APPEND TARGET_LIBRARIES "advapi32")
list(APPEND TARGET_LIBRARIES "wsock32")
list(APPEND TARGET_LIBRARIES "secur32")
list(APPEND TARGET_LIBRARIES "userenv")

add_library(${TARGET_LIB_NAME} ${HEADERS} ${SOURCES} ${RESOURCES})

set_target_properties(${TARGET_LIB_NAME} PROPERTIES
                      C_STANDARD 17
                      C_STANDARD_REQUIRED ON
)

# target_compile_options(${TARGET_NAME} PRIVATE ${TARGET_COMPILE_OPTIONS})
target_include_directories(${TARGET_LIB_NAME} PRIVATE ${TARGET_INCLUDES})
target_link_libraries (${TARGET_LIB_NAME} PRIVATE ${TARGET_LIBRARIES})
